### ISSUE TITLE
Add Examples

### ISSUE THREAD

**Issue by micahhausler** [taruti/sftpd#1]
Any chance you could add some basic examples for a starting point on how to use this library? Thanks for open sourcing it!

**Comment by taruti** [comment]
Feel free to ask for more docs & examples.

**Comment by linuxfreak003** [comment]
Is there any chance there's a rw filesystem example somewhere? I've been having a bit of trouble myself figuring out how to write to the filesystem.

**Comment by taruti** [comment]
@linuxfreak003 https://github.com/taruti/sftpd/blob/master/example/synthetic_fs.go#L93 has example code which allows overwriting the existing files. Basically
1) Allow new files in OpenFile depending on flags
2) Implement WriteAt for your file type

**Comment by linuxfreak003** [comment]
I hadn't noticed that. Thank you for pointing me in the right direction! Much appreciated.
