### ISSUE TITLE
 sftpd connection errored: ssh: no common algorithms

### ISSUE THREAD

**Issue by 756445638** [taruti/sftpd#2]
I use you the package that named "githut.com/taruti/sftpd"
# my code blow

func main(){
    e := RunServer("192.168.1.203:2200",&IMP{})
    if e !=nil{
        fmt.Printf("run failed,err:%v",e)
    }
}
// Run a server serving a given filesystem
func RunServer(hostport string, fs sftpd.FileSystem) error {
    config := &ssh.ServerConfig{
        PasswordCallback: sshutil.CreatePasswordCheck(testUser, testPass),
    }
    config.KeyExchanges = append(config.KeyExchanges,ssh.KeyAlgoDSA,ssh.KeyAlgoECDSA256,ssh.KeyAlgoECDSA384,ssh.KeyAlgoECDSA521,ssh.KeyAlgoRSA)

```
hkey, e := sshutil.KeyLoader{Flags: sshutil.Create}.Load()
if e != nil {
    return e
}

config.AddHostKey(hkey)

listener, e := net.Listen("tcp", hostport)
if e != nil {
    return e
}

log.Printf("Listening on %s user %s pass %s\n", hostport, testUser, testPass)

for {
    conn, e := listener.Accept()
    if e != nil {
        return e
    }
    go HandleConn(conn, config, fs)
}
```
# }

and i has this question blow,linux shell stdout is blow
[root@localhost bin]# ./main
2015/06/18 14:56:54 Listening on 192.168.1.203:2200 user root pass 123

2015/06/18 14:56:57 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:57:39 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:57:48 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:57:57 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:58:07 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:58:16 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:58:25 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:58:35 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:58:44 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:58:53 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:59:02 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:59:12 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:59:21 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:59:30 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:59:40 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:59:49 sftpd connection errored: ssh: no common algorithms
2015/06/18 14:59:58 sftpd connection errored: ssh: no common algorithms
2015/06/18 15:00:07 sftpd connection errored: ssh: no common algorithms
2015/06/18 15:00:17 sftpd connection errored: ssh: no common algorithms
2015/06/18 15:00:26 sftpd connection errored: ssh: no common algorithms
2015/06/18 15:00:35 sftpd connection errored: ssh: no common algorithms
2015/06/18 15:00:44 sftpd connection errored: ssh: no common algorithms
2015/06/18 15:01:57 sftpd connection errored: ssh: no common algorithms
# 

I use winscp as my client tool

I have tried very possibe algorithms in golang offcial  package <golang.org/x/crypto/ssh&gt;
I also has this error ,please tell me how i encounterd this problem,and how i can solve this problem

from yuyang
i will thank all the help i can get

**Comment by taruti** [comment]
This is caused by Winscp not supporting ECDSA host keys. If you are using sshutil consider

```
sshutil.KeyLoader{Flags: sshutil.Create|sshutil.RSA2048}.Load()
```

Note that this will generate a new host key for each run. For production consider saving your host key to disk.

This will require a recent version of sshutil, a "go get -t -u" in the sftpd directory will update it.

**Comment by 756445638** [comment]
thanks i will try this later,right now i am little occupied ,if this is solved ,i will update this issue,that is  good for the people has the same problem
