### ISSUE TITLE
read dir 

### ISSUE THREAD

**Issue by 756445638** [taruti/sftpd#3]
read dir can`t show which is directory and not parent directory 
my code is blow 

func(dir *IMPDIR)Readdir(count int)([]sftpd.NamedAttr,error){
    fmt.Printf("readdir:%v\n",dir.dir.Name())
    fis, e := dir.dir.Readdir(count)
    if e != nil {
        return nil, e
    }
    nas := make([]sftpd.NamedAttr, len(fis))
    for i, fi := range fis {
        nas[i].Name = fi.Name()
        e := nas[i].FillFrom(fi)
        if e != nil{
            fmt.Printf("fill from os.FIle failed,err:%v\n",e)
        }
    }
    return nas, nil
}

almost the same as the  sftp  package example

**Comment by taruti** [comment]
Which client are you using? Can you attach your output with `go build -a -tags debug` with updated sftpd package?

**Comment by 756445638** [comment]
I am using winSCP as my client ,and the code has "fixme",is that means it is not  finished at first place,if sftp is too hard,my company will try online http file management,thank for you help any-way

**Comment by taruti** [comment]
Looking at winSCP, I noticed at least two issues:

1) winSCP is unhappy with with empty directory listings (perhaps inserting a dummy "." and ".." would make it happier, although this is not required by the spec)

2) winSCP can give the server Realpath method paths with ".." in them which of course results in an error unless the realpath implementation in the server is prepared to deal with those.

Having a debug log of the server side would help with the `go build -a -tags debug`. But yes sftp can be quite nontrivial to use and the library interface is quite low-level.

**Comment by taruti** [comment]
https://github.com/taruti/sftpd/commit/d416715a12f684a28199e0dc6a89432deaf67032

May help if you are using the EmptyFS default Realpath implementation with winSCP.
