### ISSUE TITLE
ReadDir problem with Filezilla and ls -l, support for Long Name?

### ISSUE THREAD

**Issue by ilius** [taruti/sftpd#7]
It started after I realized that with FileZilla, directories are detected as directory only if their name starts with letter "d" (which is very strange).
Also with Linux's sftp client, "ls -l" does not show the files details (just names)

Then I come across this line and saw this FIXME
https://github.com/taruti/sftpd/blob/master/server.go#L216

The format of Long Name is simple, like
https://github.com/pkg/sftp/blob/master/server_unix.go#L129

But the marshaling/encoding syntax (`.B32` stuff) looks very strange to me. And I have no idea about the binary format.
Since we need the FileZilla problem be fixed for some of our customers, what can I do to fix this problem?

**Comment by taruti** [comment]
Will fix this later today. Thanks for the report :)

.B32String means "big-endian 32-bit length prefixed string".

Relevant spec for future reference:
```The format of the `longname' field is unspecified by this protocol.
   It MUST be suitable for use in the output of a directory listing
   command (in fact, the recommended operation for a directory listing
   command is to simply display this data).  However, clients SHOULD NOT
   attempt to parse the longname field for file attributes; they SHOULD
   use the attrs field instead.

    The recommended format for the longname field is as follows:

   	-rwxr-xr-x   1 mjos     staff      348911 Mar 25 14:29 t-filexfer
   	1234567890 123 12345678 12345678 12345678 123456789012

   Here, the first line is sample output, and the second field indicates
   widths of the various fields.  Fields are separated by spaces.  The
   first field lists file permissions for user, group, and others; the
   second field is link count; the third field is the name of the user
   who owns the file; the fourth field is the name of the group that
   owns the file; the fifth field is the size of the file in bytes; the
   sixth field (which actually may contain spaces, but is fixed to 12
   characters) is the file modification time, and the seventh field is
   the file name.  Each field is specified to be a minimum of certain
   number of character positions (indicated by the second line above),
   but may also be longer if the data does not fit in the specified
   length.
```

**Comment by taruti** [comment]
The change ended up being a little more involved, but FileZilla works fine with master now.

**Comment by ilius** [comment]
Yes it's fixed.
And making `attr.MTime` a time.Time was also good.
Thank you very much
